name: Build and Release Lua Script

on:
  push:
    branches:
      - prod
      - beta

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set OUTPUT_DIR environment variable
        run: echo "OUTPUT_DIR=%CD%\output" >> $GITHUB_ENV
        shell: cmd

      - name: Create output directory
        run: mkdir output
        shell: cmd

      - name: Run build.bat
        working-directory: ./builder
        run: build.bat "%CD%"
        shell: cmd

      - name: Create or Update Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: market.lua
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
          tag: ${{ github.ref_name == 'prod' && 'prod' || 'beta' }}
          name: ${{ github.ref_name == 'prod' && 'Production Release' || 'Beta Release' }}
